services:
  webapp:
    build:
      context: ../webapp/go
    ports:
      - "8080:8080"
    working_dir: /home/isucon/webapp/go
    depends_on:
      db:
        condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:8080 || exit 1
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isucon
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uisucon -pisucon
