services:
  webapp:
    build:
      context: ../webapp/go
    ports:
      - 8080:8080
    working_dir: /home/isucon/webapp/go
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
  db:
    image: mysql:8
    environment:
      ENV: local-dev
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isucon
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "isucon", "-pisucon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
