services:
  webapp:
    build:
      context: ../webapp/go
    ports:
      - 8080:8080
    working_dir: /home/isucon/webapp/go
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
  db:
    image: mysql:8
    environment:
      ENV: local-dev
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isucon
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uisucon -pisucon
