<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace IsuRide\Model;

use IsuRide\BaseModel;

/**
 * AppChairStats
 *
 * @package IsuRide\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class AppChairStats extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\IsuRide\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "recent_rides", "total_evaluation_avg", "total_rides_count" ],
  "type" : "object",
  "properties" : {
    "recent_rides" : {
      "type" : "array",
      "description" : "最近の乗車情報",
      "items" : {
        "$ref" : "#/components/schemas/AppChair_stats_recent_rides_inner"
      }
    },
    "total_rides_count" : {
      "type" : "integer",
      "description" : "総乗車回数"
    },
    "total_evaluation_avg" : {
      "type" : "number",
      "description" : "総評価平均"
    }
  },
  "description" : "椅子の統計情報"
}
SCHEMA;
}
