<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace IsuRide\Model;

use IsuRide\BaseModel;

/**
 * AppRide
 *
 * @package IsuRide\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class AppRide extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\IsuRide\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "created_at", "destination_coordinate", "id", "pickup_coordinate", "status", "updated_at" ],
  "properties" : {
    "id" : {
      "type" : "string",
      "description" : "ライドID"
    },
    "pickup_coordinate" : {
      "$ref" : "#/components/schemas/Coordinate"
    },
    "destination_coordinate" : {
      "$ref" : "#/components/schemas/Coordinate"
    },
    "status" : {
      "$ref" : "#/components/schemas/RideStatus"
    },
    "chair" : {
      "$ref" : "#/components/schemas/AppChair"
    },
    "created_at" : {
      "type" : "integer",
      "description" : "配車要求日時",
      "format" : "int64"
    },
    "updated_at" : {
      "type" : "integer",
      "description" : "配車要求更新日時",
      "format" : "int64"
    }
  },
  "description" : "App向けライド情報"
}
SCHEMA;
}
