<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace IsuRide\Model;

use IsuRide\BaseModel;

/**
 * OwnerGetSales200Response
 *
 * @package IsuRide\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class OwnerGetSales200Response extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\IsuRide\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "chairs", "models", "total_sales" ],
  "properties" : {
    "total_sales" : {
      "type" : "integer",
      "description" : "オーナーが管理する椅子全体の売上"
    },
    "chairs" : {
      "type" : "array",
      "description" : "椅子ごとの売上情報",
      "items" : {
        "$ref" : "#/components/schemas/owner_get_sales_200_response_chairs_inner"
      }
    },
    "models" : {
      "type" : "array",
      "description" : "モデルごとの売上情報",
      "items" : {
        "$ref" : "#/components/schemas/owner_get_sales_200_response_models_inner"
      }
    }
  }
}
SCHEMA;
}
