<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace IsuRide\Model;

use IsuRide\BaseModel;

/**
 * RequestStatus
 *
 * @package IsuRide\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class RequestStatus extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\IsuRide\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "RequestStatus",
  "type" : "string",
  "description" : "配車要求ステータス\n\nMATCHING: サービス上でマッチング処理を行なっていて椅子が確定していない\nDISPATCHING: 椅子が確定し、乗車位置に向かっている\nDISPATCHED: 椅子が乗車位置に到着して、ユーザーの乗車を待機している\nCARRYING: ユーザーが乗車し、椅子が目的地に向かっている\nARRIVED: 目的地に到着した\nCOMPLETED: ユーザーの決済・椅子評価が完了した\n",
  "enum" : [ "MATCHING", "DISPATCHING", "DISPATCHED", "CARRYING", "ARRIVED", "COMPLETED" ]
}
SCHEMA;
}
