version: "3"

includes:
  go:
    taskfile: webapp/go/Taskfile.yml
    dir: webapp/go

tasks:
  init:
    cmds:
      - go install github.com/sqldef/sqldef/cmd/mysqldef@latest
  up:
    cmds:
      - docker compose -f compose-local.yml up -d
    dir: ./development
  down:
    cmds:
      - docker compose -f compose-local.yml down -v
    dir: ./development
  migrate:
    cmds:
      - sed /^USE\ isucon\;/d < webapp/sql/1-schema.sql | mysqldef -p isucon isucon
    sources:
      - webapp/sql/1-schema.sql
    deps:
      - prepare
  backend:
    - task: go:build
    - task: go:run
