version: '3'

includes:
  go:
    taskfile: webapp/go/Taskfile.yml
    dir: webapp/go

tasks:
  init:
    cmds:
      - go install github.com/sqldef/sqldef/cmd/mysqldef@latest
  prepare:
    cmds:
      - docker compose -f compose-local.yml up -d
    dir: ./development
  prepare:down:
    cmds:
      - docker compose -f compose-local.yml down -v
    dir: ./development
  migrate:
    cmds:
      - mysqldef -p isucon isucon < webapp/sql/schema.sql
    sources:
      - webapp/sql/schema.sql
    deps:
      - prepare
  backend:
    - task: go:build
    - task: go:run
