version: "3"

tasks:
  build:
    - go build -o isuride{{exeExt}} .
  sources:
    - ./*.go
    - go.mod
    - go.sum
  run:
    - ./isuride{{exeExt}}
  run:vm:
    - go build -o isuride{{exeExt}} .
    - sudo systemctl restart isuride-go
