<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace IsuRide\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractAppApi Class Doc Comment
 *
 * @package IsuRide\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractAppApi
{
    /**
     * GET appGetNearbyChairs
     * Summary: ユーザーの近くにいる椅子を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetNearbyChairs(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $latitude = (key_exists('latitude', $queryParams)) ? $queryParams['latitude'] : null;
        $longitude = (key_exists('longitude', $queryParams)) ? $queryParams['longitude'] : null;
        $distance = (key_exists('distance', $queryParams)) ? $queryParams['distance'] : null;
        $message = "How about implementing appGetNearbyChairs as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET appGetNotification
     * Summary: ユーザー向け通知エンドポイント
     * Notes: 最新の自分のライドを取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetNotification(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing appGetNotification as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET appGetRide
     * Summary: ユーザーがライドの詳細を確認する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $rideId ライドID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetRide(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $rideId
    ): ResponseInterface {
        $message = "How about implementing appGetRide as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET appGetRides
     * Summary: ユーザーが完了済みのライド一覧を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetRides(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing appGetRides as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostPaymentMethods
     * Summary: 決済トークンの登録
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostPaymentMethods(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostPaymentMethods as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRideEvaluation
     * Summary: ユーザーがライドを評価する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $rideId ライドID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRideEvaluation(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $rideId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRideEvaluation as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRides
     * Summary: ユーザーが配車を要求する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRides(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRides as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRidesEstimatedFare
     * Summary: ライドの運賃を見積もる
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRidesEstimatedFare(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRidesEstimatedFare as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostUsers
     * Summary: ユーザーが会員登録を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostUsers(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostUsers as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
