<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace IsuRide\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractChairApi Class Doc Comment
 *
 * @package IsuRide\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractChairApi
{
    /**
     * GET chairGetNotification
     * Summary: 椅子向け通知エンドポイント
     * Notes: 椅子に配車要求を通知するなどで使う想定
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairGetNotification(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing chairGetNotification as a GET method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET chairGetRequest
     * Summary: 椅子が配車要求情報を取得する
     * Notes: 椅子向け通知エンドポイントから通知されたidの情報を取得する想定
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairGetRequest(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $message = "How about implementing chairGetRequest as a GET method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostActivate
     * Summary: 椅子が配車受付を開始する
     * Notes: 
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostActivate(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing chairPostActivate as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostCoordinate
     * Summary: 椅子が位置情報を送信する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostCoordinate(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostCoordinate as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostDeactivate
     * Summary: 椅子が配車受付を停止する
     * Notes: 
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostDeactivate(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing chairPostDeactivate as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostRegister
     * Summary: 椅子登録を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostRegister(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostRegister as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostRequestAccept
     * Summary: 椅子が配車要求を受理する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostRequestAccept(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $message = "How about implementing chairPostRequestAccept as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostRequestDeny
     * Summary: 椅子が配車要求を拒否する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostRequestDeny(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $message = "How about implementing chairPostRequestDeny as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostRequestDepart
     * Summary: 椅子が配車位置から出発する(ユーザーが乗車完了した)
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostRequestDepart(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $message = "How about implementing chairPostRequestDepart as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
