<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace IsuRide\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractChairApi Class Doc Comment
 *
 * @package IsuRide\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractChairApi
{
    /**
     * GET chairGetNotification
     * Summary: 椅子向け通知エンドポイント
     * Notes: 椅子に配車要求を通知するなどで使う想定
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairGetNotification(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing chairGetNotification as a GET method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET chairGetRide
     * Summary: 椅子がライド情報を取得する
     * Notes: 椅子向け通知エンドポイントから通知されたidの情報を取得する想定
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $rideId ライドID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairGetRide(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $rideId
    ): ResponseInterface {
        $message = "How about implementing chairGetRide as a GET method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostActivity
     * Summary: 椅子が配車受付を開始・停止する
     * Notes: 
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostActivity(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostActivity as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostChairs
     * Summary: オーナーが椅子の登録を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostChairs(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostChairs as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostCoordinate
     * Summary: 椅子が自身の位置情報を送信する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostCoordinate(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostCoordinate as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST chairPostRideStatus
     * Summary: 椅子がライドのステータスを更新する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $rideId ライドID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function chairPostRideStatus(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $rideId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing chairPostRideStatus as a POST method in IsuRide\Api\ChairApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
