<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace IsuRide\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractAppApi Class Doc Comment
 *
 * @package IsuRide\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractAppApi
{
    /**
     * GET appGetNearbyChairs
     * Summary: ユーザーの近くにいる椅子を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetNearbyChairs(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $latitude = (key_exists('latitude', $queryParams)) ? $queryParams['latitude'] : null;
        $longitude = (key_exists('longitude', $queryParams)) ? $queryParams['longitude'] : null;
        $distance = (key_exists('distance', $queryParams)) ? $queryParams['distance'] : null;
        $message = "How about implementing appGetNearbyChairs as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET appGetNotification
     * Summary: ユーザー向け通知エンドポイント
     * Notes: 最新の自分の配車要求を取得します。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetNotification(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing appGetNotification as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET appGetRequest
     * Summary: ユーザーが配車要求の状態を確認する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appGetRequest(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $message = "How about implementing appGetRequest as a GET method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostPaymentMethods
     * Summary: 決済トークンの登録
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostPaymentMethods(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostPaymentMethods as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRegister
     * Summary: ユーザーが会員登録を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRegister(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRegister as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRequest
     * Summary: ユーザーが配車要求を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRequest(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRequest as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRequestEstimate
     * Summary: リクエストの運賃を見積もる
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRequestEstimate(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRequestEstimate as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST appPostRequestEvaluate
     * Summary: ユーザーが椅子を評価する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $requestId 配車要求ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function appPostRequestEvaluate(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $requestId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing appPostRequestEvaluate as a POST method in IsuRide\Api\AppApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
