<?php

/**
 * ISURIDE API Specification
 * PHP version 7.4
 *
 * @package IsuRide
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace IsuRide\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractOwnerApi Class Doc Comment
 *
 * @package IsuRide\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractOwnerApi
{
    /**
     * GET ownerGetChair
     * Summary: 管理している椅子の詳細を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $chairId 椅子ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function ownerGetChair(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $chairId
    ): ResponseInterface {
        $message = "How about implementing ownerGetChair as a GET method in IsuRide\Api\OwnerApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET ownerGetChairs
     * Summary: 椅子のオーナーが管理している椅子の一覧を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function ownerGetChairs(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing ownerGetChairs as a GET method in IsuRide\Api\OwnerApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET ownerGetSales
     * Summary: 椅子のオーナーが指定期間の全体・椅子ごと・モデルごとの売上情報を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function ownerGetSales(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $since = (key_exists('since', $queryParams)) ? $queryParams['since'] : null;
        $until = (key_exists('until', $queryParams)) ? $queryParams['until'] : null;
        $message = "How about implementing ownerGetSales as a GET method in IsuRide\Api\OwnerApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST ownerPostOwners
     * Summary: 椅子のオーナーが会員登録を行う
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function ownerPostOwners(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing ownerPostOwners as a POST method in IsuRide\Api\OwnerApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
