# kubernetes 用のビルド設定ファイル
defaultPlatforms:
   - linux/arm64
   - linux/amd64
 
 builds:
   - id: bench
     dir: .
     main: .
     ldflags:
       - -s
       - -w
       - -X github.com/yuta-otsubo/isucon-sutra/bench/cmd.version={{.Git.ShortCommit}}

