version: "3"

tasks:
  run-local:
    cmds:
      - go run . run --target http://localhost:8080 -t 60
  build:
    cmds:
      - go build -ldflags "-s -w"
  test:
    cmds:
      - go test ./...
  image-build:
    cmds:
      - ko build -L .
