# Go言語で実装されたタスクランナー
# brew install go-task でインストールする必要がある
version: '3'
tasks:
  run-local:
    cmds:
      - go run . run --target http://localhost:8080 -t 10
  build:
    cmds:
      - go build  -ldflags "-s -w"
  test:
    cmds:
      - go test ./...
  image-build:
    cmds:
      - ko build -L .
