version: '3'
tasks:
  run-local:
    cmds:
      - go run . run --target http://localhost:8080
    buld:
      cmds:
        - go build  -ldflags "-s -w"
    image-build:
      cmds:
        - ko build -L .

