version: "3"

tasks:
  run-local:
    cmds:
      - go run . run --target http://localhost:8080 -t 60 {{.CLI_ARGS}}
  build:
    cmds:
      - go build -ldflags "-s -w"
  build-linux-amd64:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ./bin/bench_linux_amd64
  test:
    cmds:
      - go test ./...
  image-build:
    cmds:
      - ko build -L .
  gen:
    cmds:
      - go generate ./...
