requires 'perl', '5.040';

requires 'Kossy', '0.63';
requires 'Starlet', '0.31';
requires 'HTTP::Status', '7.00';
requires 'Type::Tiny', '2.006000';
requires 'Cpanel::JSON::XS', '4.38';

# DB
requires 'DBD::mysql', '5.009';
requires 'DBIx::Sunny', '0.9993';

requires 'HTTP::Parser::XS', '0.17';

requires 'Data::ULID::XS', '1.000'
