name: Build Base Image with Packer

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: [isucon14-ci-packer-base]
    name: build isucon14 base image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install unzip
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.11.2"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Build
        run: |
          cd provisioning/packer
          packer init -upgrade isucon14_base_image.pkr.hcl
          packer build isucon14_base_image.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
