name: Front-end CI
on:
    push:
        paths:
            - frontend/**/*
defaults:
    run:
        working-directory: ./frontend
jobs:
    build:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pnpm install
            - run: pnpm run lint
            - run: pnpm run fmtcheck
            - run: pnpm run typecheck
